"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nabat_ml_gui.py']
OPTIONS = {
    'iconfile': 'assets/pulse_round.icns'
}
REQUIRES = [
    'librosa==0.8.0',
    'tensorflow==2.4.1',
    'matplotlib==3.3.4',
    'py2app==0.24',
    'requests==2.25.1'
]
PACKAGES = ['prediction', 'spectrogram', 'nabat']
DATA_FILES = ['prediction', 'spectrogram', 'nabat', 'assets']

setup(
    app=APP,
    author='Ben Gotthold',
    author_email='bgotthold@usgs.gov',
    url='https://sciencebase.usgs.gov/nabat/',
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    packages=PACKAGES,
    include_package_data=True,
    setup_requires=REQUIRES
)
